### ISSUE TITLE
Update Swiftlint

### ISSUE THREAD

**Issue by artemnovichkov** [artemnovichkov/swift-project-template#52]
Add Swiftlint rules:
```yml
type_contents_order:
  order:
    - case
    - associated_type
    - type_alias
    - subtype
    - [type_property, instance_property]
    - [initializer, type_method, view_life_cycle_method, subscript, other_method, ib_action]

file_header:
  required_pattern: |
                    \/\/
                    \/\/  Copyright © \d{4}\ .*?. All rights reserved.
                    \/\/
```
